# Generated by Django 2.1.3 on 2018-11-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMS_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schclass',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
