# Generated by Django 2.1.3 on 2018-11-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GAMS_webapp', '0002_schclass_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='datetime_created',
        ),
        migrations.AddField(
            model_name='grades',
            name='schclass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schclass', to='GAMS_webapp.SchClass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='GAMS_webapp.UserExt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='GAMS_webapp.UserExt'),
        ),
    ]
