# Generated by Django 2.1.3 on 2018-11-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GAMS_webapp', '0003_auto_20181108_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmonitor',
            name='schclass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schclass_parent_monitor', to='GAMS_webapp.SchClass'),
            preserve_default=False,
        ),
    ]
