# Generated by Django 2.1.3 on 2018-11-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMS_webapp', '0004_parentmonitor_schclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmonitor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
